name: Docker CI Pipeline

on: push

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v3

      - name: Step 2 - Build Docker image
        run: docker build -t my-python-app .

      - name: Step 3 - Run Docker container
        run: docker run my-python-app
